version: '3'

volumes:
  pg_data:
  static:
  kittygram_final_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: hutji/kittygram_final-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - kittygram_final_media:/app/media/
  frontend:
    image: hutji/kittygram_final-frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: hutji/kittygram_final-gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - kittygram_final_media:/app/media/
